In [1]:
myNums = [10,14,12,0,4,7,8]

In [ ]:
3*myNums # copies list instead of multuplying each element by 3
3*myNums[0] #can multpliy the first element by 3

[10, 14, 12, 0, 4, 7, 8, 10, 14, 12, 0, 4, 7, 8, 10, 14, 12, 0, 4, 7, 8]

In [ ]:
#try looping through each element and multiply by 3
newNums = [] #create new list
for num in myNums:
   newNums.append(num*3) #store the multiplied value

In [5]:
newNums

[30, 42, 36, 0, 12, 21, 24]

In [6]:
import numpy as np

In [11]:
#make a list an array
myArray = np.array(myNums)*3 #multiply each element by 3

In [ ]:
myArray # arrays are more for mathmaticians. 

array([30, 42, 36,  0, 12, 21, 24])

Trying different opperations on myArray
 - Add, subtract, etc,
 - Can you add an array with another array

In [20]:
myArray + 3 #add 3 to each element

array([33, 45, 39,  3, 15, 24, 27])

In [21]:
otherArray = np.array([1,45,6,3,8,9])

myArray + otherArray #add the two arrays together
#Error1: arrays must be the same size to add them together


ValueError: operands could not be broadcast together with shapes (7,) (6,) 

In [22]:
otherArray = np.array([1,45,6,3,8,10,9])

myArray + otherArray #add the arrays

array([31, 87, 42,  3, 20, 31, 33])

In [23]:
myArray - otherArray #subtract the arrays

array([29, -3, 30, -3,  4, 11, 15])

In [18]:
myArray * otherArray #multiply the arrays

array([  30, 1890,  216,    0,   96,  210,  216])

In [19]:
myArray / otherArray #divide the arrays

array([30.        ,  0.93333333,  6.        ,  0.        ,  1.5       ,
        2.1       ,  2.66666667])