In [701]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [702]:
data = pd.read_csv('floridaHousePrices.csv', index_col='Index')
data.head()
#don't use quadrant
#don't use taxes

,Price,Size,Lotsize,Taxes,Bedrooms,Baths,Quadrant
Index,,,,,,,
1,145000,1240,18000,1360,3,2.0,NW
2,68000,370,25000,1050,1,1.0,NW
3,115000,1130,25000,1010,3,1.5,NW
4,69000,1120,17000,830,3,2.0,SW
5,163000,1710,14000,2150,3,2.0,NW


In [703]:
data['Size2'] = data['Size'] ** 2

In [704]:
#sklearn requires you to split the data into features and target
#x = data[['Size', 'Lotsize', 'Size2']] # 25896.334256595095
x = data[['Bedrooms', 'Lotsize', 'Size2', 'Size']] # 21790.008623985552
#x = data[['Size', 'Bedrooms', 'Size2']] # 24817.318033698786
y = data['Price']

In [705]:
#spliting the data into training and testing sets, sklearn has a function for it
from sklearn.model_selection import train_test_split

#prepping the data in advance
#usually more data for training is better 

In [706]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [707]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape #70%, 30%

((70, 4), (70,), (30, 4), (30,))

In [708]:
#linregress function equivalent in sklearn
from sklearn.linear_model import LinearRegression

In [709]:
model = LinearRegression()


In [710]:
model

LinearRegression()

In [711]:
model.fit(x_train, y_train)

LinearRegression()

In [712]:
model.coef_ #slope (m)
#for each increase in square footage, the price increases by $74
#for each increase in number of baths, the price increases by $8,418

array([-7.77791569e+02,  2.39399636e+00, -1.29953176e-02,  1.15318585e+02])

In [713]:
model.intercept_ #y-intercept (b)

-56146.07618562304

In [714]:
model.score(x_test, y_test) #R^2 score

0.3777256616318435

In [715]:
model.predict(x_test) #predicting the y values for the test set (cost prediction)

array([232715.30256831,  68308.68150806,  88406.89575876, 106233.9281275 ,
       119003.84836762,  95742.9609318 , 137323.68014077, 167694.21382731,
       114730.58163609, 125213.50587922, 143225.35620201,  43814.85876418,
       105318.94636091, 128350.89682833, 110137.79877113, 115189.25199149,
       176741.69669294, 134899.74369932, 107032.62189391,  63887.76761801,
       202588.40700116,  68967.93066728,  91482.98175923, 126819.04605351,
       109776.95553965, 113243.52409283, 131076.61442109, 208170.51493904,
       105416.41710591, 149623.75324397])

In [716]:
from sklearn.metrics import mean_squared_error as mse

In [717]:
np.sqrt(mse(y_test, model.predict(x_test))) #mean squared error

30007.601404857225

TESTING DIFFERENT MODELS

BEST SQUARED (MSE) USING LINEAR REGRESSION ---> 21790.008623985552 ('Bedrooms', 'Lotsize', 'Size2', 'Size')

In [718]:
#import Quantile Regression sklearn
from sklearn.linear_model import QuantileRegressor
from sklearn.metrics import mean_squared_error as mse


In [ ]:
quantile = 0.25
model = QuantileRegressor(quantile=quantile)
model.fit(x_train, y_train)
#model.coef_ #slope (m)
#model.intercept_ #y-intercept (b)
#model.score(x_test, y_test) #R^2 score
model.predict(x_test) #predicting the y values for the test set (cost prediction)

array([188212.81016802,  56335.23588433,  71108.62694005,  87437.64045046,
        96190.68305323,  78165.06244556, 111266.88891263, 135519.74998234,
        94429.74579939, 100000.        , 116496.91257983,  31759.98703465,
        85301.59884905, 103882.46888587,  90010.10700039,  95656.78028252,
       141848.0360024 , 108881.23201646,  87083.17428442,  52698.09195623,
       164034.85751692,  54847.49321401,  74010.37635742, 102621.84942806,
        89620.20974538,  91079.32949564, 105735.01958384, 168930.16771663,
        85299.04018354, 123375.22177817])

In [ ]:
np.sqrt(mse(y_test, model.predict(x_test))) #mean squared error
#Lowest (0.5) so far ---> 24941.148890462086 
#Lowest (0.75) so far ---> 23670.877657248857
#Lowest (0.25) so far ---> 29242.870536735474

29242.870536735474